[package]
name = "minigrep"
version = "0.1.0"
authors = ["Idan <idang1410@gmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
